export const voices = [
  {
    id: 1,
    name: "Angelo",
    image: "https://cdn-frontend.trendyuu.com/public/voices/angelo.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Angelo.webm",
    gender: "male",
    nationality: "brazilian",
    language: "portuguese",
    usage: "conteúdo geral, narração natural e neutra",
  },
  {
    id: 2,
    name: "Natalia",
    image: "https://cdn-frontend.trendyuu.com/public/voices/natalia.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Natalia.webm",
    gender: "female",
    nationality: "spanish",
    language: "spanish",
    usage: "vídeos femininos, estilo influencer",
  },
  {
    id: 3,
    name: "Adriana",
    image: "https://cdn-frontend.trendyuu.com/public/voices/adriana.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Adriana.webm",
    gender: "female",
    nationality: "brazilian",
    language: "portuguese",
    usage: "voz suave, ideal para storytelling",
  },
  {
    id: 4,
    name: "Evelin",
    image: "https://cdn-frontend.trendyuu.com/public/voices/evelin.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Evelin.webm",
    gender: "female",
    nationality: "brazilian",
    language: "portuguese",
    usage: "voz jovem brasileira, ideal para TikTok e Reels",
  },
  {
    id: 5,
    name: "Silveira Santos",
    image: "https://cdn-frontend.trendyuu.com/public/voices/silveira.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Silveira.webm",
    gender: "male",
    nationality: "brazilian",
    language: "portuguese",
    usage: "locutor profissional, estilo apresentador classico",
  },
  {
    id: 6,
    name: "Carlos Rocha",
    image: "https://cdn-frontend.trendyuu.com/public/voices/rocha.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Rocha.webm",
    gender: "male",
    nationality: "brazilian",
    language: "portuguese",
    usage: "voz grave para videos motivacionais e narracao forte",
  },
  {
    id: 7,
    name: "Yasmin Araujo",
    image: "https://cdn-frontend.trendyuu.com/public/voices/yasmin.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Yasmin.webm",
    gender: "female",
    nationality: "brazilian",
    language: "portuguese",
    usage: "influencer vibe, videos femininos modernos",
  },
  {
    id: 8,
    name: "Lair Souza",
    image: "https://cdn-frontend.trendyuu.com/public/voices/lair.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Lair.webm",
    gender: "male",
    nationality: "brazilian",
    language: "portuguese",
    usage: "voz de radio, perfeita para conteudo serio e institucional",
  },
  // vozes internacionais renumeradas a partir do 9
  {
    id: 9,
    name: "Stacy",
    image: "https://cdn-frontend.trendyuu.com/public/voices/stacy.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Stacy.webm",
    gender: "female",
    nationality: "american",
    language: "english",
    usage: "vídeos elegantes, estilo britânico",
  },
  {
    id: 10,
    name: "Chad",
    image: "https://cdn-frontend.trendyuu.com/public/voices/chad.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Chad.webm",
    gender: "male",
    nationality: "american",
    language: "english",
    usage: "conteúdo motivacional e masculino forte",
  },
  {
    id: 11,
    name: "Olivia",
    image: "https://cdn-frontend.trendyuu.com/public/voices/olivia.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Olivia.webm",
    gender: "female",
    nationality: "american",
    language: "english",
    usage: "vídeos femininos modernos e narrativas leves",
  },
  {
    id: 12,
    name: "Grace",
    image: "https://cdn-frontend.trendyuu.com/public/voices/grace.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Grace.webm",
    gender: "female",
    nationality: "american",
    language: "english",
    usage: "conteúdo profissional, clean e claro",
  },
  {
    id: 13,
    name: "Zack",
    image: "https://cdn-frontend.trendyuu.com/public/voices/zack.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Zack.webm",
    gender: "male",
    nationality: "australian",
    language: "english",
    usage: "vídeos de aventura, energia alta",
  },
  {
    id: 14,
    name: "Finn",
    image: "https://cdn-frontend.trendyuu.com/public/voices/carlos.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Finn.webm",
    gender: "male",
    nationality: "british",
    language: "english",
    usage: "locução britânica premium",
  },
  {
    id: 15,
    name: "Leon",
    image: "https://cdn-frontend.trendyuu.com/public/voices/leon.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Leon.webm",
    gender: "male",
    nationality: "american",
    language: "english",
    usage: "conteúdo de tecnologia e reviews",
  },
  {
    id: 16,
    name: "Alex",
    image: "https://cdn-frontend.trendyuu.com/public/voices/alex.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Alex.webm",
    gender: "female",
    nationality: "american",
    language: "english",
    usage: "vídeos femininos descontraídos",
  },
  {
    id: 17,
    name: "James",
    image: "https://cdn-frontend.trendyuu.com/public/voices/james.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/James.webm",
    gender: "male",
    nationality: "american",
    language: "english",
    usage: "narração séria e institucional",
  },
  {
    id: 18,
    name: "Ellin",
    image: "https://cdn-frontend.trendyuu.com/public/voices/ellin.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Ellin.webm",
    gender: "female",
    nationality: "swedish",
    language: "swedish",
    usage: "vídeos minimalistas e estéticos",
  },
  {
    id: 19,
    name: "Claire",
    image: "https://cdn-frontend.trendyuu.com/public/voices/claire.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Claire.webm",
    gender: "female",
    nationality: "british",
    language: "english",
    usage: "locução britânica elegante",
  },
  {
    id: 20,
    name: "Nina",
    image: "https://cdn-frontend.trendyuu.com/public/voices/nina.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Nina.webm",
    gender: "female",
    nationality: "american",
    language: "english",
    usage: "voz jovem, perfeita para TikTok",
  },
  {
    id: 21,
    name: "Owen",
    image: "https://cdn-frontend.trendyuu.com/public/voices/owen.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Owen.webm",
    gender: "male",
    nationality: "american",
    language: "english",
    usage: "voz neutra para qualquer tipo de vídeo",
  },
  {
    id: 22,
    name: "Zara",
    image: "https://cdn-frontend.trendyuu.com/public/voices/zara.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Zara.webm",
    gender: "female",
    nationality: "american",
    language: "english",
    usage: "vídeos femininos fortes e confiantes",
  },
  {
    id: 23,
    name: "Joel",
    image: "https://cdn-frontend.trendyuu.com/public/voices/joel.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Joel.webm",
    gender: "male",
    nationality: "american",
    language: "english",
    usage: "narração profunda e masculina",
  },
  {
    id: 24,
    name: "Matt",
    image: "https://cdn-frontend.trendyuu.com/public/voices/matt.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Matt.webm",
    gender: "male",
    nationality: "american",
    language: "english",
    usage: "vídeos explicativos e corporativos",
  },
  {
    id: 25,
    name: "Jace",
    image: "https://cdn-frontend.trendyuu.com/public/voices/jace.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Jace.webm",
    gender: "male",
    nationality: "american",
    language: "english",
    usage: "narrativas rápidas e jovens",
  },
  {
    id: 26,
    name: "Jhon",
    image: "https://cdn-frontend.trendyuu.com/public/voices/jhon.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Jhon.webm",
    gender: "male",
    nationality: "british",
    language: "english",
    usage: "vídeos com tom britânico mais casual",
  },
  {
    id: 27,
    name: "Rowena",
    image: "https://cdn-frontend.trendyuu.com/public/voices/rowena.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Rowena.webm",
    gender: "female",
    nationality: "british",
    language: "english",
    usage: "voz suave, ideal para vídeos calmos",
  },
  {
    id: 28,
    name: "Bill",
    image: "https://cdn-frontend.trendyuu.com/public/voices/bill.webp",
    audio: "https://cdn-frontend.trendyuu.com/public/sound/Bill.webm",
    gender: "male",
    nationality: "american",
    language: "english",
    usage: "voz madura, documentários e narrativas sérias",
  },
];
